test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,12 +7,17 @@ jobs:
 
   job-a:
     runs-on: ubuntu-latest
-    if: ${{ false }}
+    if: ${{ true }}
 
     steps:
       - name: Debug
         run: |
           echo "Step 1"
+
+      - name: Fail
+        run: |
+          echo "Fail"
+          exit 1
 
   job-b:
     needs: [ job-a ]
